# A catppuccin RC for tmux. In beta, specs may change. 
app_name: tmux
binary_name: tmux 
installation:
  location:
    macos: ~/.tmux/plugins/
    linux: ~/.tmux/plugins/ 
    windows: ~/.tmux/plugins/ # requires Cygwin
  flavours:
    all:
      default:
        - catppuccin-latte.tmuxtheme
        - catppuccin-frappe.tmuxtheme
        - catppuccin-macchiato.tmuxtheme
        - catppuccin-mocha.tmuxtheme
        - catppuccin.tmux
    latte:
      default:
        - catppucin-latte.tmuxtheme
        - catppucin.tmux
    frappe:
      default:
        - catppuccin-frappe.tmuxtheme
        - catppuccin.tmux
    macchiato:
      default:
        - catppuccin-macchiato.tmuxtheme
        - catppuccin.tmux
    mocha:
      default:
        - catppuccin-mocha.tmuxtheme
        - catppuccin.tmux
  to: tmux
  comments: "Using these theme files requires the Tmux Package Manager & using global options in your local ~/.tmux.conf file."
