name: Bug Report
description: Report your bugs with the theme here!
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue outlining your problem?
      description: Please search to see if an issue already exists for your problem.
      options:
        - label: I have searched the existing issues and they do not solve my problem.
          required: true
  - type: textarea
    attributes:
      label: Describe your problem.
      description: Also tell us, what do you expect to see?
      placeholder: The battery charging icon is missing...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Paste your configuration.
      description: Provide us with the contents of your `.tmux.conf` file.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attach screenshots.
      description: If applicable, attach screenshots which clearly highlight the issue.
  - type: input
    attributes:
      label: What tmux version are you seeing the issue on?
      description: "You can find your version by running `tmux -V`"
      placeholder: tmux 3.3a
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any additional comments?
      description: Add any information that hasn't been covered in the previous sections!
