name: Enhancement Issue
description: Request improvements to the theme here!
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue outlining your improvement?
      description: Please search to see if your improvement has already been raised as an issue.
      options:
        - label: I have searched the existing issues and my improvement has not been raised yet.
          required: true
  - type: textarea
    attributes:
      label: What would you like to see added and/or changed?
      description: Make sure to mention why you think this is an improvement!
      placeholder: I'd like to have an extra configuration option for...
    validations:
      required: true
