# vim:set ft=tmux:
%hidden MODULE_NAME="application"

set -ogq "@catppuccin_${MODULE_NAME}_icon" " "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{@thm_maroon}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #{pane_current_command}"

source -F "#{d:current_file}/../utils/status_module.conf"
